name: Routine

on:
  schedule:
    # updates runs at UTC 06:00, creating notion journals 1hr before updates
    - cron: '5 5 * * * '
  # for manual trigger
  workflow_dispatch:

jobs:
  routine:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: 'yarn'

      - name: Create Dev Journals
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        run: yarn routine dev_journal

      - name: Live long and prosper
        uses: gautamkrishnar/keepalive-workflow@v1
        with:
          commit_message: "devops - auto keepalive before 60 days of inactivity"
          committer_email: "runzhou.li@gmail.com"
